<template>
  <v-app>
    <v-app-bar app color="primary" dark>
      <v-spacer></v-spacer>
      <div v-if="editUser && showEdit">
        <EditUserInfo @updateUser="addNewUser($event)" />
      </div>
      <div>
        <SignInUser
          :isSignIn="isSignInValue"
          @clicked-show-detail="clickedShowDetailModal($event)"
          @changeState="changeSignOut($event)"
        />
      </div>
    </v-app-bar>

    <v-main>
      <UserRecord :User="User" />
      <br />
      <GameRecord :User="User" />
    </v-main>
  </v-app>
</template>

<script>
import _ from "lodash";
import UserRecord from "./components/UserRecord";
import SignInUser from "./components/SignInUser.vue";
import EditUserInfo from "./components/EditUserInfo.vue";
import GameRecord from "./components/GameData.vue";
export default {
  name: "App",
  components: {
    UserRecord,
    EditUserInfo,
    SignInUser,
    GameRecord,
  },
  props: ["isSignIn"],

  data: () => ({
    editUser: false,
    showEdit: true,
    isSignInValue: false,
    currentUser: "",
    User: [
      {
        name: "Ashutosh",
        contact: "9191919191",
        Age: "24",
        TotalMatch: "25",
        BlackPiece: "14",
        WhitePiece: "11",
        BestGame: "45",
        WinGame: "18",
        LostGame: "7",
        BlackWin: "12",
        WhiteWin: "6",
        BestGameRecord: {
          PlayerName1: "Ashutosh",
          PlayerName2: "Kiran",
          Win: "Ashutosh",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "45",
        },

        WinPercentage: "72",
      },
      {
        name: "Kiran",
        contact: "9191919190",
        Age: "25",
        TotalMatch: "30",
        BlackPiece: "18",
        WhitePiece: "12",
        BestGame: "38",
        WinGame: "20",
        LostGame: "10",
        BlackWin: "12",
        WhiteWin: "8",
        WinPercentage: "66",
        BestGameRecord: {
          PlayerName1: "Kiran",
          PlayerName2: "Abhay",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "38",
        },
      },
      {
        name: "Piyush",
        contact: "9191919199",
        Age: "26",
        TotalMatch: "100",
        BlackPiece: "51",
        WhitePiece: "49",
        BestGame: "35",
        WinGame: "60",
        LostGame: "40",
        BlackWin: "25",
        WhiteWin: "35",
        WinPercentage: "60",
        BestGameRecord: {
          PlayerName1: "Piyush",
          PlayerName2: "Ankit",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "35",
        },
      },
      {
        name: "Shri Dhar",
        contact: "9191919198",
        Age: "27",
        TotalMatch: "70",
        BlackPiece: "40",
        WhitePiece: "30",
        BestGame: "29",
        WinGame: "30",
        LostGame: "40",
        BlackWin: "10",
        WhiteWin: "20",
        WinPercentage: "42",
        BestGameRecord: {
          PlayerName1: "Shri Dhar",
          PlayerName2: "Ankit",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "29",
        },
      },
      {
        name: "Siddesh",
        contact: "9191919197",
        Age: "24",
        TotalMatch: "60",
        BlackPiece: "30",
        WhitePiece: "30",
        BestGame: "40",
        WinGame: "35",
        LostGame: "25",
        BlackWin: "17",
        WhiteWin: "18",
        WinPercentage: "58",
        BestGameRecord: {
          PlayerName1: "Shri Dhar",
          PlayerName2: "Ankit",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "29",
        },
      },
      {
        name: "Rahul",
        contact: "9191919196",
        Age: "18",
        TotalMatch: "50",
        BlackPiece: "25",
        WhitePiece: "25",
        BestGame: "44",
        WinGame: "20",
        LostGame: "30",
        BlackWin: "8",
        WhiteWin: "12",
        WinPercentage: "40",
        BestGameRecord: {
          PlayerName1: "Rahul",
          PlayerName2: "Shri Dhar",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "44",
        },
      },
      {
        name: "Vansh",
        contact: "9191919195",
        Age: "24",
        TotalMatch: "60",
        BlackPiece: "35",
        WhitePiece: "25",
        BestGame: "50",
        WinGame: "39",
        LostGame: "21",
        BlackWin: "17",
        WhiteWin: "22",
        WinPercentage: "65",
        BestGameRecord: {
          PlayerName1: "Vansh",
          PlayerName2: "Ajay",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "50",
        },
      },
      {
        name: "Samay",
        contact: "9191919194",
        Age: "26",
        TotalMatch: "55",
        BlackPiece: "30",
        WhitePiece: "25",
        BestGame: "17",
        WinGame: "40",
        LostGame: "15",
        BlackWin: "17",
        WhiteWin: "23",
        WinPercentage: "72",
        BestGameRecord: {
          PlayerName1: "Samay",
          PlayerName2: "Arun",
          Win: "Samay",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "17",
        },
      },

      {
        name: "Sagar",
        contact: "9191919193",
        Age: "23",
        TotalMatch: "10",
        BlackPiece: "5",
        WhitePiece: "5",
        BestGame: "30",
        WinGame: "1",
        LostGame: "9",
        BlackWin: "0",
        WhiteWin: "1",
        WinPercentage: "10",
        BestGameRecord: {
          PlayerName1: "Sagar",
          PlayerName2: "Aman",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "30",
        },
      },
      {
        name: "Prateek",
        contact: "9191919192",
        Age: "27",
        TotalMatch: "62",
        BlackPiece: "32",
        WhitePiece: "30",
        BestGame: "22",
        WinGame: "20",
        LostGame: "42",
        BlackWin: "12",
        WhiteWin: "8",
        WinPercentage: "32",
        BestGameRecord: {
          PlayerName1: "Prateek",
          PlayerName2: "Aman",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "22",
        },
      },
      {
        name: "Bhargava",
        contact: "9191919189",
        Age: "32",
        TotalMatch: "100",
        BlackPiece: "38",
        WhitePiece: "62",
        BestGame: "25",
        WinGame: "60",
        LostGame: "40",
        BlackWin: "30",
        WhiteWin: "30",
        WinPercentage: "60",
        BestGameRecord: {
          PlayerName1: "Bhargava",
          PlayerName2: "Aman",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "25",
        },
      },
      {
        name: "Pavan",
        contact: "9191919188",
        Age: "31",
        TotalMatch: "41",
        BlackPiece: "22",
        WhitePiece: "19",
        BestGame: "48",
        WinGame: "17",
        LostGame: "24",
        BlackWin: "5",
        WhiteWin: "12",
        WinPercentage: "41",
        BestGameRecord: {
          PlayerName1: "Pavan",
          PlayerName2: "Raj",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "48",
        },
      },
      {
        name: "Hafeez",
        contact: "9191919187",
        Age: "31",
        TotalMatch: "56",
        BlackPiece: "32",
        WhitePiece: "24",
        BestGame: "30",
        WinGame: "30",
        LostGame: "20",
        BlackWin: "20",
        WhiteWin: "10",
        WinPercentage: "54",

        BestGameRecord: {
          PlayerName1: "Hafeez",
          PlayerName2: "Pavan",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "30",
        },
      },
      {
        name: "Chaitanya",
        contact: "9191919186",
        Age: "45",
        TotalMatch: "70",
        BlackPiece: "35",
        WhitePiece: "35",
        BestGame: "40",
        WinGame: "40",
        LostGame: "30",
        BlackWin: "20",
        WhiteWin: "20",
        WinPercentage: "57",
        BestGameRecord: {
          PlayerName1: "Chaitanya",
          PlayerName2: "Ron",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "40",
        },
      },
      {
        name: "Chintan",
        contact: "9191919186",
        Age: "47",
        TotalMatch: "80",
        BlackPiece: "40",
        WhitePiece: "40",
        BestGame: "25",
        WinGame: "60",
        LostGame: "20",
        BlackWin: "30",
        WhiteWin: "30",
        WinPercentage: "75",
        BestGameRecord: {
          PlayerName1: "Chintan",
          PlayerName2: "Vansh",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "25",
        },
      },
      {
        name: "Gaurav",
        contact: "9191919184",
        Age: "20",
        TotalMatch: "40",
        BlackPiece: "20",
        WhitePiece: "20",
        BestGame: "35",
        WinGame: "12",
        LostGame: "28",
        BlackWin: "6",
        WhiteWin: "6",
        WinPercentage: "30",
        BestGameRecord: {
          PlayerName1: "Gaurav",
          PlayerName2: "Vansh",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "35",
        },
      },
      {
        name: "Ashish",
        contact: "9191919183",
        Age: "18",
        TotalMatch: "18",
        BlackPiece: "8",
        WhitePiece: "10",
        BestGame: "54",
        WinGame: "10",
        LostGame: "8",
        BlackWin: "5",
        WhiteWin: "5",
        WinPercentage: "55",
        BestGameRecord: {
          PlayerName1: "Ashish",
          PlayerName2: "Kirra",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "54",
        },
      },
      {
        name: "Nelsion",
        contact: "9191919182",
        Age: "25",
        TotalMatch: "16",
        BlackPiece: "28",
        WhitePiece: "28",
        BestGame: "45",
        WinGame: "2",
        LostGame: "14",
        BlackWin: "2",
        WhiteWin: "0",
        WinPercentage: "12",
        BestGameRecord: {
          PlayerName1: "Nelsion",
          PlayerName2: "Aman",
          Win: "Kiran",
          Time: "11 AM",
          Date: "12 Sept 2021",
          Pl1Color: "Black",
          Pl2Color: "White",
          BestGame: "45",
        },
      },
    ],
  }),

  methods: {
    clickedShowDetailModal(SignInUser) {
      this.currentUser = SignInUser;
      if (!_.isEmpty(SignInUser)) {
        this.editUser = true;
        this.isSignInValue = true;
      }
    },

    changeSignOut(ele) {
      if (ele === true) {
        this.editUser = false;
        this.isSignInValue = false;
      }
    },
    addNewUser(ele) {
      console.log("ele>>>>>>>>>>>>>>>>>>>>>>>>>>>>", ele);
      this.User.map((data, index) => {
        if (data.name === this.currentUser);
        {
          this.User[index] = ele;
          this.$forceUpdate();
        }
      });

      console.log(this.User);
    },
  },
};
</script>
